apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellovue-deployment
  labels:
    role: helloRole
spec:
  replicas: 3
  selector:
    matchLabels:
      role: helloRole
  template:
    metadata:
      labels:
        role: helloRole
    spec:
      containers:
        - name: deploy-container
          image: mprambadi/hello-vue
          ports:
            - containerPort: 80